# GENERATED by scripts/gen_proto_python.py from schemas/. DO NOT EDIT.
"""Generated DireWolf protocol types.

Every module here is generated from the JSON Schemas in ``schemas/``, which are in
turn emitted from the Rust crate ``dwk-proto``. To change a message, change the Rust
type and run ``make schema``. Hand edits are overwritten, and CI rejects them.
"""

from __future__ import annotations

from typing import Final

from direwolf.proto import dwcp, dwkp, events, operations

__all__ = ["SCHEMA_DIGEST", "dwcp", "dwkp", "events", "operations"]

SCHEMA_DIGEST: Final = "sha256:772e6b7087442cd7e4db706fbef097146a653917678cf4f140f60760eca0bc11"
"""Digest of every schema these bindings were generated from."""
