# GENERATED by scripts/gen_proto_python.py from schemas/. DO NOT EDIT.
"""Generated DireWolf protocol types.

Every module here is generated from the JSON Schemas in ``schemas/``, which are in
turn emitted from the Rust crate ``dwk-proto``. To change a message, change the Rust
type and run ``make schema``. Hand edits are overwritten, and CI rejects them.
"""

from __future__ import annotations

from typing import Final

from direwolf.proto import dwcp, dwkp, events, operations

__all__ = ["SCHEMA_DIGEST", "dwcp", "dwkp", "events", "operations"]

SCHEMA_DIGEST: Final = "sha256:4c374460b00f1a1e5bb247b49c021b8e2b08de7a7860a3c6a5b1336a57f33b7a"
"""Digest of every schema these bindings were generated from."""
