# GENERATED by scripts/gen_proto_python.py from schemas/. DO NOT EDIT.
"""Generated DireWolf protocol types.

Every module here is generated from the JSON Schemas in ``schemas/``, which are in
turn emitted from the Rust crate ``dwk-proto``. To change a message, change the Rust
type and run ``make schema``. Hand edits are overwritten, and CI rejects them.
"""

from __future__ import annotations

from typing import Final

from direwolf.proto import dwcp, dwkp, events, operations

__all__ = ["SCHEMA_DIGEST", "dwcp", "dwkp", "events", "operations"]

SCHEMA_DIGEST: Final = "sha256:286a8845b4c576060ab936b9d5b8f1296993199110fc0af8a4d41ce75cee0c71"
"""Digest of every schema these bindings were generated from."""
