# GENERATED by scripts/gen_proto_python.py from schemas/dwcp/. DO NOT EDIT.
# Source digest: sha256:3ad24485f0cc0f510a0b06470984a25f89a13a1ce577bb1f4b3d3a119f47847b
"""DWCP -- the client protocol. Forward-compatible: unknown fields are preserved."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Final, Self

from direwolf.wire import envelope, validate
from direwolf.wire.envelope import MessageSpec, Rules
from direwolf.wire.errors import VersionRange
from direwolf.wire.strict_json import JsonValue
from direwolf.wire.validate import Cx

__all__ = [
    "MESSAGES",
    "ClientError",
]


_CLIENTERROR_CODE = validate.text(64, '^[A-Z][A-Z0-9_]{0,63}$', None)
_CLIENTERROR_DETAIL = validate.text(512, None, None)
_CLIENTERROR_RETRYABLE = validate.boolean


@dataclass(frozen=True, slots=True, kw_only=True)
class ClientError:
    """A request failed, or the gateway is reporting a problem."""

    code: str
    """An open-ended error code; clients must accept codes newer than they are."""
    detail: str
    """Human-readable explanation."""
    retryable: bool
    """Whether retrying the same request may succeed."""
    extensions: dict[str, JsonValue] = field(default_factory=dict)
    """Members this version does not declare, preserved for re-emission."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, extensions = validate.partition(obj, ('code', 'detail', 'retryable'), True, cx)
        code_ = validate.take_required(known, 'code', cx, _CLIENTERROR_CODE)
        detail_ = validate.take_required(known, 'detail', cx, _CLIENTERROR_DETAIL)
        retryable_ = validate.take_required(known, 'retryable', cx, _CLIENTERROR_RETRYABLE)
        return cls(code=code_, detail=detail_, retryable=retryable_, extensions=extensions)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['code'] = self.code
        out['detail'] = self.detail
        out['retryable'] = self.retryable
        for key, member in self.extensions.items():
            out[key] = member
        return out


MESSAGES: Final[Mapping[tuple[str, str], tuple[MessageSpec, ...]]] = MappingProxyType({
    ('response', 'direwolf.error'): (
        MessageSpec(
            schema='direwolf.error',
            message_type='response',
            versions=VersionRange(1, 1),
            rules=Rules('optional', 'optional', 'optional', 'optional', 'forbidden', 'forbidden'),
            payload=ClientError,
        ),
    ),
})
"""Every message of this family the build knows, keyed by (type, schema): one spec
per version range, in ascending order."""


def decode(data: bytes) -> envelope.DwcpMessage:
    """Decode a DWCP message, preserving undeclared members."""
    return envelope.decode_dwcp(data, MESSAGES)


def encode(message: envelope.DwcpMessage) -> bytes:
    """Canonical bytes, re-emitting every preserved member."""
    return envelope.encode_dwcp(message)
