# GENERATED by scripts/gen_proto_python.py from schemas/dwkp/. DO NOT EDIT.
# Source digest: sha256:3562f35b15453594795b21fc765b92a73d79cf71a96eb77f5011372523037055
"""DWKP -- the kernel protocol. Strict: unknown fields and operations are rejected."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Final, Self

from direwolf.wire import envelope, validate
from direwolf.wire.envelope import MessageSpec, Rules
from direwolf.wire.errors import VersionRange
from direwolf.wire.strict_json import JsonValue
from direwolf.wire.validate import Cx

__all__ = [
    "MESSAGES",
    "Ack",
    "AdmitRun",
    "AuthorityDecision",
    "AuthorityQuery",
    "AuthorityRefusal",
    "CanonicalPreview",
    "CanonicalPreviewResult",
    "CapabilityGrant",
    "EffectiveAuthority",
    "FsReadCall",
    "FsReadResult",
    "Handshake",
    "HandshakeAccepted",
    "HeartbeatPayload",
    "LeaseAcquire",
    "LeaseGrant",
    "LeaseRelease",
    "ProtocolErrorPayload",
    "ReleaseRun",
    "RunGrant",
    "ToolAction",
    "ToolDecision",
    "ToolDenial",
    "ToolFailure",
    "ToolInvoke",
    "ToolRefusal",
    "ToolResult",
    "VersionSpan",
    "WithheldCapability",
]


_AUTHORITYDECISION_EFFECT = validate.enumeration(('ALLOW', 'DENY'))
_AUTHORITYDECISION_REASON = validate.enumeration(('ALLOWED_BY_RULE', 'DENIED_BY_RULE', 'DEFAULT_DENY', 'NO_CAPABILITY'))
_AUTHORITYDECISION_CAPABILITY_RESULT = validate.enumeration(('SATISFIED', 'NOT_SATISFIED'))
_AUTHORITYDECISION_POLICY_RESULT = validate.enumeration(('SATISFIED', 'NOT_SATISFIED'))
_AUTHORITYDECISION_RULE_ID = validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None)
_AUTHORITYDECISION_RULE_SOURCE = validate.text(256, '^[A-Za-z0-9._/-]{1,240}:[0-9]{1,8}$', None)
_AUTHORITYDECISION_REQUIRED_CAPABILITY = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthorityDecision:
    """One authority decision, with everything needed to explain it. Never a bare boolean.
    POLICY.md §1.5 requires the matched rule, its source and the capability that was
    required, because a denial nobody can debug is a denial someone will route around.
    """

    effect: str
    """What was decided."""
    reason: str
    """Why, as a classifiable code rather than prose."""
    capability_result: str
    """Whether a held capability covers the action (ADR-0006 gate one)."""
    policy_result: str
    """Whether policy permits it (ADR-0006 gate two). Both gates always run: an ALLOW needs
    both, and neither substitutes for the other.
    """
    rule_id: str
    """The id of the rule that produced the effect: the matched rule, the narrowing
    postcondition, or the policy's own mandatory `default` rule when nothing matched
    before it. Never a stand-in for a rule that did not run (ADR-0040).
    """
    rule_source: str
    """Where that rule is written: file and line."""
    required_capability: str
    """The capability the action needed. Always present: a decision is only ever made about
    a canonical action, and every canonical action requires one (ADR-0040; optional in
    version 1).
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('effect', 'reason', 'capability_result', 'policy_result', 'rule_id', 'rule_source', 'required_capability'), False, cx)
        effect_ = validate.take_required(known, 'effect', cx, _AUTHORITYDECISION_EFFECT)
        reason_ = validate.take_required(known, 'reason', cx, _AUTHORITYDECISION_REASON)
        capability_result_ = validate.take_required(known, 'capability_result', cx, _AUTHORITYDECISION_CAPABILITY_RESULT)
        policy_result_ = validate.take_required(known, 'policy_result', cx, _AUTHORITYDECISION_POLICY_RESULT)
        rule_id_ = validate.take_required(known, 'rule_id', cx, _AUTHORITYDECISION_RULE_ID)
        rule_source_ = validate.take_required(known, 'rule_source', cx, _AUTHORITYDECISION_RULE_SOURCE)
        required_capability_ = validate.take_required(known, 'required_capability', cx, _AUTHORITYDECISION_REQUIRED_CAPABILITY)
        return cls(effect=effect_, reason=reason_, capability_result=capability_result_, policy_result=policy_result_, rule_id=rule_id_, rule_source=rule_source_, required_capability=required_capability_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['effect'] = self.effect
        out['reason'] = self.reason
        out['capability_result'] = self.capability_result
        out['policy_result'] = self.policy_result
        out['rule_id'] = self.rule_id
        out['rule_source'] = self.rule_source
        out['required_capability'] = self.required_capability
        return out


_CAPABILITYGRANT_CAP_ID = validate.identifier('cap')
_CAPABILITYGRANT_CAPABILITY = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class CapabilityGrant:
    """One capability the kernel granted, and the id it minted for it."""

    cap_id: str
    """The kernel's handle for this grant, recorded against every decision it covers. A
    request never presents one: `ToolInvoke` names a call, and the authority finds the
    covering grant itself (ADR-0043), so the id proves nothing and selects nothing.
    """
    capability: str
    """The granted capability, which may be narrower than the one asked for. Never wider:
    that is the ⊑ invariant the kernel enforces.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('cap_id', 'capability'), False, cx)
        cap_id_ = validate.take_required(known, 'cap_id', cx, _CAPABILITYGRANT_CAP_ID)
        capability_ = validate.take_required(known, 'capability', cx, _CAPABILITYGRANT_CAPABILITY)
        return cls(cap_id=cap_id_, capability=capability_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['cap_id'] = self.cap_id
        out['capability'] = self.capability
        return out


_FSREADCALL_PATH = validate.text(384, '^/[^\\u0000]{0,383}$', None)
_FSREADCALL_MAX_BYTES = validate.integer(1, 262144)


@dataclass(frozen=True, slots=True, kw_only=True)
class FsReadCall:
    """An `fs.read`: read at most `max_bytes` from the start of one regular file in the
    run's workspace.
    """

    path: str
    """The file, in the logical namespace: `/workspace/...`. The authority canonicalises it
    (ADR-0042); nothing here is trusted.
    """
    max_bytes: int
    """The most bytes to read. The authority decides on this bound before anything is read:
    it is the `max_bytes` of the capability the read requires and the `byte_count`
    policy evaluates.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('path', 'max_bytes'), False, cx)
        path_ = validate.take_required(known, 'path', cx, _FSREADCALL_PATH)
        max_bytes_ = validate.take_required(known, 'max_bytes', cx, _FSREADCALL_MAX_BYTES)
        return cls(path=path_, max_bytes=max_bytes_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['path'] = self.path
        out['max_bytes'] = self.max_bytes
        return out


_FSREADRESULT_CONTENT = validate.text(524288, '^(?:[0-9a-f]{2})*$', None)
_FSREADRESULT_EOF_OBSERVED = validate.boolean


@dataclass(frozen=True, slots=True, kw_only=True)
class FsReadResult:
    """What an `fs.read` returned."""

    content: str
    """The bytes read from the start of the file, exactly, as hexadecimal. At most the
    call's `max_bytes`; their count is the content's length, and is not repeated.
    """
    eof_observed: bool
    """Whether the end of the file was **observed** during this read: a read returned no
    bytes before `max_bytes` were read. `false` when exactly `max_bytes` were read — the
    end was then not proven, because finding it would have meant reading past the
    authorised bound, and the broker never does (ADR-0043).
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('content', 'eof_observed'), False, cx)
        content_ = validate.take_required(known, 'content', cx, _FSREADRESULT_CONTENT)
        eof_observed_ = validate.take_required(known, 'eof_observed', cx, _FSREADRESULT_EOF_OBSERVED)
        return cls(content=content_, eof_observed=eof_observed_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['content'] = self.content
        out['eof_observed'] = self.eof_observed
        return out


_TOOLACTION_TOOL = validate.enumeration(('fs.read',))
_TOOLACTION_CANONICAL_PATH = validate.text(384, '^/[^\\u0000]{0,383}$', None)
_TOOLACTION_BYTE_COUNT = validate.integer(1, 262144)
_TOOLACTION_ENVIRONMENT = validate.enumeration(('HOST', 'SANDBOX'))


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolAction:
    """The canonical action the authority built from a tool call: every fact policy decided
    on, stated by the authority, never echoed from the request. The capability the
    action required is exactly `<tool>:<canonical_path>?max_bytes=<byte_count>`. It is
    not repeated as capability text, because a canonical path may hold characters the
    capability grammar's ASCII form cannot, and a truncated or re-spelled copy would be
    a second spelling of one fact.
    """

    tool: str
    """The tool."""
    canonical_path: str
    """The object's canonical path: the one spelling the grammar accepts, verified name by
    name where the object was resolved.
    """
    byte_count: int
    """The byte bound the action was decided with."""
    environment: str
    """Where it runs."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('tool', 'canonical_path', 'byte_count', 'environment'), False, cx)
        tool_ = validate.take_required(known, 'tool', cx, _TOOLACTION_TOOL)
        canonical_path_ = validate.take_required(known, 'canonical_path', cx, _TOOLACTION_CANONICAL_PATH)
        byte_count_ = validate.take_required(known, 'byte_count', cx, _TOOLACTION_BYTE_COUNT)
        environment_ = validate.take_required(known, 'environment', cx, _TOOLACTION_ENVIRONMENT)
        return cls(tool=tool_, canonical_path=canonical_path_, byte_count=byte_count_, environment=environment_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['tool'] = self.tool
        out['canonical_path'] = self.canonical_path
        out['byte_count'] = self.byte_count
        out['environment'] = self.environment
        return out


_TOOLDECISION_EFFECT = validate.enumeration(('ALLOW', 'DENY'))
_TOOLDECISION_REASON = validate.enumeration(('ALLOWED_BY_RULE', 'DENIED_BY_RULE', 'DEFAULT_DENY', 'NO_CAPABILITY', 'UNRESOLVED_POLICY_INPUT'))
_TOOLDECISION_CAPABILITY_RESULT = validate.enumeration(('SATISFIED', 'NOT_SATISFIED'))
_TOOLDECISION_POLICY_RESULT = validate.enumeration(('SATISFIED', 'NOT_SATISFIED'))
_TOOLDECISION_RULE_ID = validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None)
_TOOLDECISION_RULE_SOURCE = validate.text(256, '^[A-Za-z0-9._/-]{1,240}:[0-9]{1,8}$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolDecision:
    """How the two gates of ADR-0006 decided a tool action. Both always run."""

    effect: str
    """What was decided."""
    reason: str
    """Why."""
    capability_result: str
    """Whether a held capability covers the action."""
    policy_result: str
    """Whether policy permits it. `REQUIRE_APPROVAL` does not: nothing in this build can
    obtain an approval (M6).
    """
    rule_id: str
    """The rule that produced the effect, or could not be evaluated."""
    rule_source: str
    """Where that rule is written."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('effect', 'reason', 'capability_result', 'policy_result', 'rule_id', 'rule_source'), False, cx)
        effect_ = validate.take_required(known, 'effect', cx, _TOOLDECISION_EFFECT)
        reason_ = validate.take_required(known, 'reason', cx, _TOOLDECISION_REASON)
        capability_result_ = validate.take_required(known, 'capability_result', cx, _TOOLDECISION_CAPABILITY_RESULT)
        policy_result_ = validate.take_required(known, 'policy_result', cx, _TOOLDECISION_POLICY_RESULT)
        rule_id_ = validate.take_required(known, 'rule_id', cx, _TOOLDECISION_RULE_ID)
        rule_source_ = validate.take_required(known, 'rule_source', cx, _TOOLDECISION_RULE_SOURCE)
        return cls(effect=effect_, reason=reason_, capability_result=capability_result_, policy_result=policy_result_, rule_id=rule_id_, rule_source=rule_source_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['effect'] = self.effect
        out['reason'] = self.reason
        out['capability_result'] = self.capability_result
        out['policy_result'] = self.policy_result
        out['rule_id'] = self.rule_id
        out['rule_source'] = self.rule_source
        return out


_VERSIONSPAN_MIN = validate.integer(1, 65535)
_VERSIONSPAN_MAX = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class VersionSpan:
    """A range of versions a receiver supports."""

    min: int
    """Lowest supported version."""
    max: int
    """Highest supported version."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('min', 'max'), False, cx)
        min_ = validate.take_required(known, 'min', cx, _VERSIONSPAN_MIN)
        max_ = validate.take_required(known, 'max', cx, _VERSIONSPAN_MAX)
        validate.ordered('min', min_, 'max', max_, cx)
        return cls(min=min_, max=max_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['min'] = self.min
        out['max'] = self.max
        return out


_WITHHELDCAPABILITY_CAPABILITY = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)
_WITHHELDCAPABILITY_REASON = validate.enumeration(('NOT_IN_AGENT_PROFILE', 'NOT_IN_SKILL_SET', 'NOT_IN_PARENT_GRANT', 'ABOVE_PROFILE_CEILING', 'DENIED_BY_POLICY', 'UNRESOLVED_RESOURCE'))


@dataclass(frozen=True, slots=True, kw_only=True)
class WithheldCapability:
    """One capability that was asked for and not granted, and which term of the minting
    expression removed it.
    """

    capability: str
    """The capability as requested."""
    reason: str
    """Which intersection removed it."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('capability', 'reason'), False, cx)
        capability_ = validate.take_required(known, 'capability', cx, _WITHHELDCAPABILITY_CAPABILITY)
        reason_ = validate.take_required(known, 'reason', cx, _WITHHELDCAPABILITY_REASON)
        return cls(capability=capability_, reason=reason_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['capability'] = self.capability
        out['reason'] = self.reason
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class Ack:
    """Acknowledges a request that has no other result."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_ADMITRUN_AGENT_PROFILE = validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None)
_ADMITRUN_SKILLS = validate.sequence(32, validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None))
_ADMITRUN_REQUESTED_CAPABILITIES = validate.sequence(64, validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None))


@dataclass(frozen=True, slots=True, kw_only=True)
class AdmitRun:
    """Asks the kernel to admit a run and mint its authority. `requested_capabilities` is a
    request, not an assertion: the kernel intersects it with the agent profile, the
    skills, the parent grant and the profile ceiling, and returns what survived
    (`CAPABILITIES.md` §4, `mint` step 5). Asking for more is not an error, because an
    error invites a retry loop; it yields less, and the difference is reported. There is
    no `mode`, `profile`, `workspace_sensitivity`, `taint` or `privacy_class` field.
    Those are policy inputs, and ADR-0028 makes every policy input kernel-derived: a
    field here would be the runtime asserting one.
    """

    agent_profile: str
    """Which agent profile the run is for. The kernel resolves it to the profile's declared
    capabilities; an unknown name is a denial, not a protocol error.
    """
    skills: list[str]
    """The skills to activate. Skills only ever narrow."""
    requested_capabilities: list[str]
    """The capabilities the run would like. May exceed what it can have."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('agent_profile', 'skills', 'requested_capabilities'), False, cx)
        agent_profile_ = validate.take_required(known, 'agent_profile', cx, _ADMITRUN_AGENT_PROFILE)
        skills_ = validate.take_required(known, 'skills', cx, _ADMITRUN_SKILLS)
        requested_capabilities_ = validate.take_required(known, 'requested_capabilities', cx, _ADMITRUN_REQUESTED_CAPABILITIES)
        return cls(agent_profile=agent_profile_, skills=skills_, requested_capabilities=requested_capabilities_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['agent_profile'] = self.agent_profile
        skills_out: list[JsonValue] = list(self.skills)
        out['skills'] = skills_out
        requested_capabilities_out: list[JsonValue] = list(self.requested_capabilities)
        out['requested_capabilities'] = requested_capabilities_out
        return out


_AUTHORITYQUERY_PROPOSED = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthorityQuery:
    """Asks what a run may do, and optionally whether one specific action is permitted.
    Read-only in both shapes. It reports authority and grants none, touches no resource,
    reserves nothing and performs no effect: it is the question M3 exists to answer,
    asked without doing anything about the answer.
    """

    proposed: str | None = None
    """A proposed action, in the kernel's capability grammar. When absent the response
    reports effective authority only. When present, the response is a `decision` for
    exactly this action **only if** the authority can construct the complete canonical
    action it names; otherwise it is `direwolf.authority.refused` with
    `NO_CANONICAL_ACTION`. Through M3e that is every proposal, because capability text
    alone never determines one (ADR-0040).
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('proposed',), False, cx)
        proposed_ = validate.take_optional(known, 'proposed', cx, _AUTHORITYQUERY_PROPOSED)
        return cls(proposed=proposed_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        if self.proposed is not None:
            out['proposed'] = self.proposed
        return out


_AUTHORITYREFUSAL_OPERATION = validate.enumeration(('ACQUIRE_LEASE', 'RELEASE_LEASE', 'HEARTBEAT', 'ADMIT_RUN', 'RELEASE_RUN', 'QUERY_AUTHORITY'))
_AUTHORITYREFUSAL_REASON = validate.enumeration(('STALE_EPOCH', 'LEASE_HELD', 'IDEMPOTENCY_CONFLICT', 'ADMISSION_ENDED', 'UNKNOWN_AGENT_PROFILE', 'UNKNOWN_RUN', 'NO_CANONICAL_ACTION'))
_AUTHORITYREFUSAL_PAIRING = {
    'ACQUIRE_LEASE': ('LEASE_HELD',),
    'RELEASE_LEASE': ('STALE_EPOCH',),
    'HEARTBEAT': ('STALE_EPOCH',),
    'ADMIT_RUN': ('STALE_EPOCH', 'IDEMPOTENCY_CONFLICT', 'ADMISSION_ENDED', 'UNKNOWN_AGENT_PROFILE'),
    'RELEASE_RUN': ('STALE_EPOCH',),
    'QUERY_AUTHORITY': ('STALE_EPOCH', 'UNKNOWN_RUN', 'NO_CANONICAL_ACTION'),
}


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthorityRefusal:
    """The authority declined to act on a well-formed request. **Three different things a
    caller must be able to tell apart**, and this is the middle one: *
    `direwolf.protocol.error` — the bytes did not form a valid message. Nothing was
    evaluated because nothing arrived. The remedy is to fix the message. * **this** —
    the message was valid and the authority's own state does not permit the operation to
    be attempted. No policy ran, no capability was consulted. The remedy is named by
    `reason` and is usually to re-acquire a lease, admit a run, or stop retrying. *
    `direwolf.authority.effective` carrying a `DENY` decision — both gates of ADR-0006
    ran against real state and refused. The remedy is to ask for less, or to change
    policy. Merging any two of those to save a message type would leave a caller unable
    to choose between three different remedies, and the failure mode of guessing is a
    retry loop against a refusal that will never change. **Two fields, and no third.**
    There is no `detail` string, no `hint`, no map: `ProtocolErrorPayload` carries a
    detail because a malformed message needs a human to repair *a message*, whereas a
    refusal needs the caller to take one of five known actions. Every byte beyond the
    reason is a byte the authority tells a caller about state the caller could not
    otherwise see — which is how a refusal becomes an oracle. `STALE_EPOCH` in
    particular does **not** carry the kernel's current epoch: handing a fenced runtime
    the one value it needs to un-fence itself would undo the fencing.
    """

    operation: str
    """Which operation was refused. Redundant with `causation_id` for a caller that still
    has the request; not redundant for an audit record, and it is what closes the
    pairing below.
    """
    reason: str
    """Why. Closed, and narrower still per operation."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('operation', 'reason'), False, cx)
        operation_ = validate.take_required(known, 'operation', cx, _AUTHORITYREFUSAL_OPERATION)
        reason_ = validate.take_required(known, 'reason', cx, _AUTHORITYREFUSAL_REASON)
        validate.paired('operation', operation_, 'reason', reason_, _AUTHORITYREFUSAL_PAIRING, cx)
        return cls(operation=operation_, reason=reason_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['operation'] = self.operation
        out['reason'] = self.reason
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class CanonicalPreview:
    """Asks what an invocation would mean, without performing it: the same canonical action
    and the same two gates `ToolInvoke` uses, and never an effect, a broker contact or
    an authorisation. **Information, not authority**: nothing in the answer is presented
    later, and an invocation decides again from scratch.
    """

    fs_read: FsReadCall
    """The `fs.read` call, exactly as `ToolInvoke` would carry it."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('fs_read',), False, cx)
        fs_read_ = validate.take_required(known, 'fs_read', cx, FsReadCall.decode)
        return cls(fs_read=fs_read_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['fs_read'] = self.fs_read.encode()
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class CanonicalPreviewResult:
    """What an invocation would mean. The path was resolved beneath the run's pinned root
    (never opened for reading) and both gates ran on the canonical action it names.
    Nothing was performed. A path that does not resolve is a `ToolRefusal` instead.
    """

    action: ToolAction
    """The canonical action `ToolInvoke` would decide on."""
    decision: ToolDecision
    """How the gates decided it now."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('action', 'decision'), False, cx)
        action_ = validate.take_required(known, 'action', cx, ToolAction.decode)
        decision_ = validate.take_required(known, 'decision', cx, ToolDecision.decode)
        return cls(action=action_, decision=decision_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['action'] = self.action.encode()
        out['decision'] = self.decision.encode()
        return out


_EFFECTIVEAUTHORITY_RUN_ID = validate.identifier('run')
_EFFECTIVEAUTHORITY_EPOCH = validate.integer(1, 9007199254740991)
_EFFECTIVEAUTHORITY_POLICY_REVISION = validate.text(64, '^[0-9a-f]{64}$', None)
_EFFECTIVEAUTHORITY_PROFILE = validate.enumeration(('SAFE', 'BALANCED', 'POWER'))


@dataclass(frozen=True, slots=True, kw_only=True)
class EffectiveAuthority:
    """What a run may do, as the kernel currently records it."""

    run_id: str
    """The run this describes."""
    epoch: int
    """The epoch the answer is current at. An answer is about a moment."""
    policy_revision: str
    """Which policy produced it."""
    profile: str
    """The ceiling the run was admitted under."""
    granted: list[CapabilityGrant]
    """What the run holds."""
    withheld: list[WithheldCapability]
    """What it asked for and did not get."""
    decision: AuthorityDecision | None = None
    """The decision for the `proposed` action, present exactly when the query carried one
    the authority could decide. A proposal it cannot decide is refused instead
    (`NO_CANONICAL_ACTION`), so an `EffectiveAuthority` answering a proposal always
    carries its decision. A reader that asked and received none must treat the answer as
    unusable rather than as an allow.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('run_id', 'epoch', 'policy_revision', 'profile', 'granted', 'withheld', 'decision'), False, cx)
        run_id_ = validate.take_required(known, 'run_id', cx, _EFFECTIVEAUTHORITY_RUN_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _EFFECTIVEAUTHORITY_EPOCH)
        policy_revision_ = validate.take_required(known, 'policy_revision', cx, _EFFECTIVEAUTHORITY_POLICY_REVISION)
        profile_ = validate.take_required(known, 'profile', cx, _EFFECTIVEAUTHORITY_PROFILE)
        granted_ = validate.take_required(known, 'granted', cx, validate.sequence(64, CapabilityGrant.decode))
        withheld_ = validate.take_required(known, 'withheld', cx, validate.sequence(64, WithheldCapability.decode))
        decision_ = validate.take_optional(known, 'decision', cx, AuthorityDecision.decode)
        return cls(run_id=run_id_, epoch=epoch_, policy_revision=policy_revision_, profile=profile_, granted=granted_, withheld=withheld_, decision=decision_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['run_id'] = self.run_id
        out['epoch'] = self.epoch
        out['policy_revision'] = self.policy_revision
        out['profile'] = self.profile
        granted_out: list[JsonValue] = [item.encode() for item in self.granted]
        out['granted'] = granted_out
        withheld_out: list[JsonValue] = [item.encode() for item in self.withheld]
        out['withheld'] = withheld_out
        if self.decision is not None:
            out['decision'] = self.decision.encode()
        return out


_HANDSHAKE_MIN_VERSION = validate.integer(1, 65535)
_HANDSHAKE_MAX_VERSION = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class Handshake:
    """Opens a DWKP connection by offering a range of envelope versions. Always sent in
    envelope version 1, whatever it offers, so that any receiver can read the offer.
    """

    min_version: int
    """Lowest envelope version the sender speaks."""
    max_version: int
    """Highest envelope version the sender speaks."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('min_version', 'max_version'), False, cx)
        min_version_ = validate.take_required(known, 'min_version', cx, _HANDSHAKE_MIN_VERSION)
        max_version_ = validate.take_required(known, 'max_version', cx, _HANDSHAKE_MAX_VERSION)
        validate.ordered('min_version', min_version_, 'max_version', max_version_, cx)
        return cls(min_version=min_version_, max_version=max_version_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['min_version'] = self.min_version
        out['max_version'] = self.max_version
        return out


_HANDSHAKEACCEPTED_VERSION = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class HandshakeAccepted:
    """Accepts a handshake, naming the version both sides will use: the highest both
    support at or above the receiver's floor.
    """

    version: int
    """The negotiated envelope version."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('version',), False, cx)
        version_ = validate.take_required(known, 'version', cx, _HANDSHAKEACCEPTED_VERSION)
        return cls(version=version_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['version'] = self.version
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class HeartbeatPayload:
    """Renews the session lease named in the envelope at the epoch named in the envelope.
    Carries nothing else.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseAcquire:
    """Requests the single-writer lease for the session named in the envelope. The kernel
    assigns the epoch; the sender cannot propose one.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_LEASEGRANT_SESSION_ID = validate.identifier('ses')
_LEASEGRANT_EPOCH = validate.integer(1, 9007199254740991)


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseGrant:
    """The lease the kernel granted."""

    session_id: str
    """The session the lease is for."""
    epoch: int
    """The epoch the kernel assigned. Every later request for the session carries it; a
    request carrying an older one is fenced (§3).
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('session_id', 'epoch'), False, cx)
        session_id_ = validate.take_required(known, 'session_id', cx, _LEASEGRANT_SESSION_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _LEASEGRANT_EPOCH)
        return cls(session_id=session_id_, epoch=epoch_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['session_id'] = self.session_id
        out['epoch'] = self.epoch
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseRelease:
    """Surrenders the lease named in the envelope, at the epoch named in the envelope. Can
    only reduce authority.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_PROTOCOLERRORPAYLOAD_CODE = validate.enumeration(('PROTOCOL_FRAME_EMPTY', 'PROTOCOL_FRAME_TOO_LARGE', 'PROTOCOL_FRAME_TRUNCATED', 'PROTOCOL_CONTENT_TYPE_UNSUPPORTED', 'PROTOCOL_INVALID_UTF8', 'PROTOCOL_INVALID_JSON', 'PROTOCOL_DUPLICATE_KEY', 'PROTOCOL_MAX_DEPTH_EXCEEDED', 'PROTOCOL_NUMBER_OUT_OF_DOMAIN', 'PROTOCOL_VERSION_UNSUPPORTED', 'PROTOCOL_UNKNOWN_OPERATION', 'PROTOCOL_SCHEMA_VIOLATION'))
_PROTOCOLERRORPAYLOAD_VIOLATION = validate.enumeration(('UNKNOWN_FIELD', 'MISSING_FIELD', 'FORBIDDEN_FIELD', 'WRONG_TYPE', 'NULL_NOT_ALLOWED', 'OUT_OF_RANGE', 'TOO_LONG', 'INVALID_FORMAT', 'UNKNOWN_VARIANT', 'TOO_MANY_ITEMS', 'INCONSISTENT'))
_PROTOCOLERRORPAYLOAD_PATH = validate.text(256, '^(/[\\s\\S]*)?$', None)
_PROTOCOLERRORPAYLOAD_DETAIL = validate.text(512, None, None)


@dataclass(frozen=True, slots=True, kw_only=True)
class ProtocolErrorPayload:
    """The message did not decode. This is **not** a policy denial: nothing was evaluated,
    because there was nothing well-formed to evaluate.
    """

    code: str
    """Stable error code."""
    violation: str | None = None
    """Finer classification for schema and version failures."""
    path: str | None = None
    """JSON Pointer to the failing location."""
    detail: str
    """Short explanation. Informational; bounded."""
    supported: VersionSpan | None = None
    """For version failures, the range the receiver supports."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('code', 'violation', 'path', 'detail', 'supported'), False, cx)
        code_ = validate.take_required(known, 'code', cx, _PROTOCOLERRORPAYLOAD_CODE)
        violation_ = validate.take_optional(known, 'violation', cx, _PROTOCOLERRORPAYLOAD_VIOLATION)
        path_ = validate.take_optional(known, 'path', cx, _PROTOCOLERRORPAYLOAD_PATH)
        detail_ = validate.take_required(known, 'detail', cx, _PROTOCOLERRORPAYLOAD_DETAIL)
        supported_ = validate.take_optional(known, 'supported', cx, VersionSpan.decode)
        return cls(code=code_, violation=violation_, path=path_, detail=detail_, supported=supported_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['code'] = self.code
        if self.violation is not None:
            out['violation'] = self.violation
        if self.path is not None:
            out['path'] = self.path
        out['detail'] = self.detail
        if self.supported is not None:
            out['supported'] = self.supported.encode()
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class ReleaseRun:
    """Ends a run's authority. The run is named by the envelope. Carries nothing: it can
    only surrender authority, and a field here would be a way to say something about a
    run while ending it.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_RUNGRANT_RUN_ID = validate.identifier('run')
_RUNGRANT_EPOCH = validate.integer(1, 9007199254740991)
_RUNGRANT_POLICY_REVISION = validate.text(64, '^[0-9a-f]{64}$', None)
_RUNGRANT_PROFILE = validate.enumeration(('SAFE', 'BALANCED', 'POWER'))


@dataclass(frozen=True, slots=True, kw_only=True)
class RunGrant:
    """The authority the kernel minted for a run. Everything here is kernel-assigned. The
    run id, the epoch and every `cap_id` are the kernel's; the runtime cannot propose
    any of them.
    """

    run_id: str
    """The run the kernel admitted."""
    epoch: int
    """The epoch this grant is fenced to. A request carrying an older one is rejected
    (`PROTOCOL.md` §3).
    """
    policy_revision: str
    """Which policy was in force when the grant was minted."""
    profile: str
    """The ceiling the run was admitted under."""
    granted: list[CapabilityGrant]
    """What the run holds."""
    withheld: list[WithheldCapability]
    """What it asked for and did not get, so it can say so coherently."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('run_id', 'epoch', 'policy_revision', 'profile', 'granted', 'withheld'), False, cx)
        run_id_ = validate.take_required(known, 'run_id', cx, _RUNGRANT_RUN_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _RUNGRANT_EPOCH)
        policy_revision_ = validate.take_required(known, 'policy_revision', cx, _RUNGRANT_POLICY_REVISION)
        profile_ = validate.take_required(known, 'profile', cx, _RUNGRANT_PROFILE)
        granted_ = validate.take_required(known, 'granted', cx, validate.sequence(64, CapabilityGrant.decode))
        withheld_ = validate.take_required(known, 'withheld', cx, validate.sequence(64, WithheldCapability.decode))
        return cls(run_id=run_id_, epoch=epoch_, policy_revision=policy_revision_, profile=profile_, granted=granted_, withheld=withheld_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['run_id'] = self.run_id
        out['epoch'] = self.epoch
        out['policy_revision'] = self.policy_revision
        out['profile'] = self.profile
        granted_out: list[JsonValue] = [item.encode() for item in self.granted]
        out['granted'] = granted_out
        withheld_out: list[JsonValue] = [item.encode() for item in self.withheld]
        out['withheld'] = withheld_out
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolDenial:
    """The path resolved and the two gates refused the action it names. Nothing was opened
    for reading, no broker was contacted and no invocation id was minted.
    """

    action: ToolAction
    """The canonical action that was decided."""
    decision: ToolDecision
    """The refusal, with the rule that made it."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('action', 'decision'), False, cx)
        action_ = validate.take_required(known, 'action', cx, ToolAction.decode)
        decision_ = validate.take_required(known, 'decision', cx, ToolDecision.decode)
        return cls(action=action_, decision=decision_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['action'] = self.action.encode()
        out['decision'] = self.decision.encode()
        return out


_TOOLFAILURE_INVOCATION_ID = validate.identifier('inv')
_TOOLFAILURE_REASON = validate.enumeration(('OBJECT_CHANGED', 'OBJECT_UNREADABLE', 'BROKER_UNAVAILABLE', 'BROKER_PROTOCOL_ERROR', 'BROKER_EXECUTION_ERROR'))


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolFailure:
    """An `fs.read` both gates allowed, whose intent was recorded, and which did not
    produce a result. The audit record holds the detail; the caller learns the class,
    which says whether retrying can help.
    """

    invocation_id: str
    """The authority's id for the invocation that failed."""
    reason: str
    """Why."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('invocation_id', 'reason'), False, cx)
        invocation_id_ = validate.take_required(known, 'invocation_id', cx, _TOOLFAILURE_INVOCATION_ID)
        reason_ = validate.take_required(known, 'reason', cx, _TOOLFAILURE_REASON)
        return cls(invocation_id=invocation_id_, reason=reason_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['invocation_id'] = self.invocation_id
        out['reason'] = self.reason
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolInvoke:
    """Asks the authority to perform one tool call for a run. The run, the session and the
    epoch are the envelope's. **One member per tool, and this build has one tool.** A
    request naming another tool is an undeclared member and fails to decode. No
    `idempotency_key`: `fs.read` is retry-safe, so a repeated invocation is a second
    read of the same object, not a second effect (ADR-0043). A tool that is not retry-
    safe needs a key, and a new version of this message, before it can be added.
    """

    fs_read: FsReadCall
    """The `fs.read` call."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('fs_read',), False, cx)
        fs_read_ = validate.take_required(known, 'fs_read', cx, FsReadCall.decode)
        return cls(fs_read=fs_read_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['fs_read'] = self.fs_read.encode()
        return out


_TOOLREFUSAL_OPERATION = validate.enumeration(('TOOL_INVOKE', 'CANONICAL_PREVIEW'))
_TOOLREFUSAL_REASON = validate.enumeration(('STALE_EPOCH', 'UNKNOWN_RUN', 'WORKSPACE_UNBOUND', 'ROOT_REPLACED', 'ROOT_UNAVAILABLE', 'UNSUPPORTED_PLATFORM', 'PATH_OUTSIDE_WORKSPACE', 'PATH_TRAVERSAL', 'PATH_NOT_CANONICAL', 'NOT_FOUND', 'NOT_A_DIRECTORY', 'SYMLINK', 'MAGIC_LINK', 'MOUNT_CROSSING', 'NAME_MISMATCH', 'NORMALIZATION_AMBIGUITY', 'SPECIAL_FILE', 'WRONG_KIND', 'RACE', 'PERMISSION_DENIED', 'DIRECTORY_TOO_LARGE', 'IO_ERROR'))
_TOOLREFUSAL_PAIRING = {
    'TOOL_INVOKE': ('STALE_EPOCH', 'UNKNOWN_RUN', 'WORKSPACE_UNBOUND', 'ROOT_REPLACED', 'ROOT_UNAVAILABLE', 'UNSUPPORTED_PLATFORM', 'PATH_OUTSIDE_WORKSPACE', 'PATH_TRAVERSAL', 'PATH_NOT_CANONICAL', 'NOT_FOUND', 'NOT_A_DIRECTORY', 'SYMLINK', 'MAGIC_LINK', 'MOUNT_CROSSING', 'NAME_MISMATCH', 'NORMALIZATION_AMBIGUITY', 'SPECIAL_FILE', 'WRONG_KIND', 'RACE', 'PERMISSION_DENIED', 'DIRECTORY_TOO_LARGE', 'IO_ERROR'),
    'CANONICAL_PREVIEW': ('STALE_EPOCH', 'UNKNOWN_RUN', 'WORKSPACE_UNBOUND', 'ROOT_REPLACED', 'ROOT_UNAVAILABLE', 'UNSUPPORTED_PLATFORM', 'PATH_OUTSIDE_WORKSPACE', 'PATH_TRAVERSAL', 'PATH_NOT_CANONICAL', 'NOT_FOUND', 'NOT_A_DIRECTORY', 'SYMLINK', 'MAGIC_LINK', 'MOUNT_CROSSING', 'NAME_MISMATCH', 'NORMALIZATION_AMBIGUITY', 'SPECIAL_FILE', 'WRONG_KIND', 'RACE', 'PERMISSION_DENIED', 'DIRECTORY_TOO_LARGE', 'IO_ERROR'),
}


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolRefusal:
    """A tool operation the authority would not attempt: its own state refused it, or the
    path did not resolve. Nothing was performed and no broker was contacted. Distinct
    from [`ToolDenial`], where the two gates ran and refused, and from [`ToolFailure`],
    where an authorised effect did not complete.
    """

    operation: str
    """Which operation."""
    reason: str
    """Why."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('operation', 'reason'), False, cx)
        operation_ = validate.take_required(known, 'operation', cx, _TOOLREFUSAL_OPERATION)
        reason_ = validate.take_required(known, 'reason', cx, _TOOLREFUSAL_REASON)
        validate.paired('operation', operation_, 'reason', reason_, _TOOLREFUSAL_PAIRING, cx)
        return cls(operation=operation_, reason=reason_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['operation'] = self.operation
        out['reason'] = self.reason
        return out


_TOOLRESULT_INVOCATION_ID = validate.identifier('inv')


@dataclass(frozen=True, slots=True, kw_only=True)
class ToolResult:
    """An invocation the authority allowed, the broker performed on the object that was
    checked, and the authority recorded -- in that order.
    """

    invocation_id: str
    """The authority's id for this invocation."""
    action: ToolAction
    """The canonical action that was decided and performed."""
    decision: ToolDecision
    """Both gates' decision."""
    fs_read: FsReadResult
    """The `fs.read` result."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('invocation_id', 'action', 'decision', 'fs_read'), False, cx)
        invocation_id_ = validate.take_required(known, 'invocation_id', cx, _TOOLRESULT_INVOCATION_ID)
        action_ = validate.take_required(known, 'action', cx, ToolAction.decode)
        decision_ = validate.take_required(known, 'decision', cx, ToolDecision.decode)
        fs_read_ = validate.take_required(known, 'fs_read', cx, FsReadResult.decode)
        return cls(invocation_id=invocation_id_, action=action_, decision=decision_, fs_read=fs_read_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['invocation_id'] = self.invocation_id
        out['action'] = self.action.encode()
        out['decision'] = self.decision.encode()
        out['fs_read'] = self.fs_read.encode()
        return out


MESSAGES: Final[Mapping[tuple[str, str], MessageSpec]] = MappingProxyType({
    ('response', 'direwolf.ack'): MessageSpec(
        schema='direwolf.ack',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=Ack,
    ),
    ('response', 'direwolf.authority.effective'): MessageSpec(
        schema='direwolf.authority.effective',
        message_type='response',
        versions=VersionRange(2, 2),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=EffectiveAuthority,
    ),
    ('request', 'direwolf.authority.query'): MessageSpec(
        schema='direwolf.authority.query',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'required', 'required', 'forbidden'),
        payload=AuthorityQuery,
    ),
    ('response', 'direwolf.authority.refused'): MessageSpec(
        schema='direwolf.authority.refused',
        message_type='response',
        versions=VersionRange(2, 2),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=AuthorityRefusal,
    ),
    ('response', 'direwolf.handshake.accepted'): MessageSpec(
        schema='direwolf.handshake.accepted',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=HandshakeAccepted,
    ),
    ('request', 'direwolf.handshake'): MessageSpec(
        schema='direwolf.handshake',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=Handshake,
    ),
    ('request', 'direwolf.heartbeat'): MessageSpec(
        schema='direwolf.heartbeat',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'forbidden'),
        payload=HeartbeatPayload,
    ),
    ('request', 'direwolf.lease.acquire'): MessageSpec(
        schema='direwolf.lease.acquire',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseAcquire,
    ),
    ('response', 'direwolf.lease.grant'): MessageSpec(
        schema='direwolf.lease.grant',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseGrant,
    ),
    ('request', 'direwolf.lease.release'): MessageSpec(
        schema='direwolf.lease.release',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'forbidden'),
        payload=LeaseRelease,
    ),
    ('response', 'direwolf.protocol.error'): MessageSpec(
        schema='direwolf.protocol.error',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ProtocolErrorPayload,
    ),
    ('request', 'direwolf.run.admit'): MessageSpec(
        schema='direwolf.run.admit',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'required'),
        payload=AdmitRun,
    ),
    ('response', 'direwolf.run.grant'): MessageSpec(
        schema='direwolf.run.grant',
        message_type='response',
        versions=VersionRange(2, 2),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=RunGrant,
    ),
    ('request', 'direwolf.run.release'): MessageSpec(
        schema='direwolf.run.release',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'required', 'required', 'forbidden'),
        payload=ReleaseRun,
    ),
    ('response', 'direwolf.tool.denied'): MessageSpec(
        schema='direwolf.tool.denied',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ToolDenial,
    ),
    ('response', 'direwolf.tool.failed'): MessageSpec(
        schema='direwolf.tool.failed',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ToolFailure,
    ),
    ('request', 'direwolf.tool.invoke'): MessageSpec(
        schema='direwolf.tool.invoke',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'required', 'required', 'forbidden'),
        payload=ToolInvoke,
    ),
    ('request', 'direwolf.tool.preview'): MessageSpec(
        schema='direwolf.tool.preview',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'required', 'required', 'forbidden'),
        payload=CanonicalPreview,
    ),
    ('response', 'direwolf.tool.previewed'): MessageSpec(
        schema='direwolf.tool.previewed',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=CanonicalPreviewResult,
    ),
    ('response', 'direwolf.tool.refused'): MessageSpec(
        schema='direwolf.tool.refused',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ToolRefusal,
    ),
    ('response', 'direwolf.tool.result'): MessageSpec(
        schema='direwolf.tool.result',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ToolResult,
    ),
})
"""Every message of this family the build knows, keyed by (type, schema)."""


def decode_body(data: bytes) -> envelope.DwkpMessage:
    """Decode a DWKP frame body; rejects everything dwk-proto rejects."""
    return envelope.decode_dwkp(data, MESSAGES)


def encode(message: envelope.DwkpMessage) -> bytes:
    """Canonical bytes for a message, verified by re-decoding."""
    return envelope.encode_dwkp(message, MESSAGES)


def to_frame(message: envelope.DwkpMessage) -> bytes:
    """A complete frame for a message."""
    return envelope.frame_dwkp(message, MESSAGES)
