# GENERATED by scripts/gen_proto_python.py from schemas/dwkp/. DO NOT EDIT.
# Source digest: sha256:96d5e9c569a966d5f6528e95fa9c4d81fbfc3cd9a20b226084603d1703d3c883
"""DWKP -- the kernel protocol. Strict: unknown fields and operations are rejected."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Final, Self

from direwolf.wire import envelope, validate
from direwolf.wire.envelope import MessageSpec, Rules
from direwolf.wire.errors import VersionRange
from direwolf.wire.strict_json import JsonValue
from direwolf.wire.validate import Cx

__all__ = [
    "MESSAGES",
    "Ack",
    "AdmitRun",
    "AuthorityDecision",
    "AuthorityQuery",
    "AuthorityRefusal",
    "CapabilityGrant",
    "EffectiveAuthority",
    "Handshake",
    "HandshakeAccepted",
    "HeartbeatPayload",
    "LeaseAcquire",
    "LeaseGrant",
    "LeaseRelease",
    "ProtocolErrorPayload",
    "ReleaseRun",
    "RunGrant",
    "VersionSpan",
    "WithheldCapability",
]


_AUTHORITYDECISION_EFFECT = validate.enumeration(('ALLOW', 'DENY'))
_AUTHORITYDECISION_REASON = validate.enumeration(('ALLOWED_BY_RULE', 'DENIED_BY_RULE', 'DEFAULT_DENY', 'NO_CAPABILITY', 'CAPABILITY_MALFORMED'))
_AUTHORITYDECISION_CAPABILITY_RESULT = validate.enumeration(('SATISFIED', 'NOT_SATISFIED'))
_AUTHORITYDECISION_POLICY_RESULT = validate.enumeration(('SATISFIED', 'NOT_SATISFIED'))
_AUTHORITYDECISION_RULE_ID = validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None)
_AUTHORITYDECISION_RULE_SOURCE = validate.text(256, '^[A-Za-z0-9._/-]{1,240}:[0-9]{1,8}$', None)
_AUTHORITYDECISION_REQUIRED_CAPABILITY = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthorityDecision:
    """One authority decision, with everything needed to explain it. Never a bare boolean.
    POLICY.md §1.5 requires the matched rule, its source and the capability that was
    required, because a denial nobody can debug is a denial someone will route around.
    """

    effect: str
    """What was decided."""
    reason: str
    """Why, as a classifiable code rather than prose."""
    capability_result: str
    """Whether a held capability covers the action (ADR-0006 gate one)."""
    policy_result: str
    """Whether policy permits it (ADR-0006 gate two). Both gates always run: an ALLOW needs
    both, and neither substitutes for the other.
    """
    rule_id: str
    """The id of the rule that decided."""
    rule_source: str
    """Where that rule is written: file and line."""
    required_capability: str | None = None
    """The capability the action needed, when the kernel could name one. Absent when the
    proposal was not in the kernel's vocabulary at all.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('effect', 'reason', 'capability_result', 'policy_result', 'rule_id', 'rule_source', 'required_capability'), False, cx)
        effect_ = validate.take_required(known, 'effect', cx, _AUTHORITYDECISION_EFFECT)
        reason_ = validate.take_required(known, 'reason', cx, _AUTHORITYDECISION_REASON)
        capability_result_ = validate.take_required(known, 'capability_result', cx, _AUTHORITYDECISION_CAPABILITY_RESULT)
        policy_result_ = validate.take_required(known, 'policy_result', cx, _AUTHORITYDECISION_POLICY_RESULT)
        rule_id_ = validate.take_required(known, 'rule_id', cx, _AUTHORITYDECISION_RULE_ID)
        rule_source_ = validate.take_required(known, 'rule_source', cx, _AUTHORITYDECISION_RULE_SOURCE)
        required_capability_ = validate.take_optional(known, 'required_capability', cx, _AUTHORITYDECISION_REQUIRED_CAPABILITY)
        return cls(effect=effect_, reason=reason_, capability_result=capability_result_, policy_result=policy_result_, rule_id=rule_id_, rule_source=rule_source_, required_capability=required_capability_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['effect'] = self.effect
        out['reason'] = self.reason
        out['capability_result'] = self.capability_result
        out['policy_result'] = self.policy_result
        out['rule_id'] = self.rule_id
        out['rule_source'] = self.rule_source
        if self.required_capability is not None:
            out['required_capability'] = self.required_capability
        return out


_CAPABILITYGRANT_CAP_ID = validate.identifier('cap')
_CAPABILITYGRANT_CAPABILITY = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class CapabilityGrant:
    """One capability the kernel granted, and the id it minted for it."""

    cap_id: str
    """The kernel's handle for this grant. `ToolInvoke` will name it when M4 gives that
    operation a wire form; the kernel resolves it against its own record, so the id
    proves nothing by itself.
    """
    capability: str
    """The granted capability, which may be narrower than the one asked for. Never wider:
    that is the ⊑ invariant the kernel enforces.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('cap_id', 'capability'), False, cx)
        cap_id_ = validate.take_required(known, 'cap_id', cx, _CAPABILITYGRANT_CAP_ID)
        capability_ = validate.take_required(known, 'capability', cx, _CAPABILITYGRANT_CAPABILITY)
        return cls(cap_id=cap_id_, capability=capability_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['cap_id'] = self.cap_id
        out['capability'] = self.capability
        return out


_VERSIONSPAN_MIN = validate.integer(1, 65535)
_VERSIONSPAN_MAX = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class VersionSpan:
    """A range of versions a receiver supports."""

    min: int
    """Lowest supported version."""
    max: int
    """Highest supported version."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('min', 'max'), False, cx)
        min_ = validate.take_required(known, 'min', cx, _VERSIONSPAN_MIN)
        max_ = validate.take_required(known, 'max', cx, _VERSIONSPAN_MAX)
        validate.ordered('min', min_, 'max', max_, cx)
        return cls(min=min_, max=max_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['min'] = self.min
        out['max'] = self.max
        return out


_WITHHELDCAPABILITY_CAPABILITY = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)
_WITHHELDCAPABILITY_REASON = validate.enumeration(('NOT_IN_AGENT_PROFILE', 'NOT_IN_SKILL_SET', 'NOT_IN_PARENT_GRANT', 'ABOVE_PROFILE_CEILING', 'DENIED_BY_POLICY'))


@dataclass(frozen=True, slots=True, kw_only=True)
class WithheldCapability:
    """One capability that was asked for and not granted, and which term of the minting
    expression removed it.
    """

    capability: str
    """The capability as requested."""
    reason: str
    """Which intersection removed it."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('capability', 'reason'), False, cx)
        capability_ = validate.take_required(known, 'capability', cx, _WITHHELDCAPABILITY_CAPABILITY)
        reason_ = validate.take_required(known, 'reason', cx, _WITHHELDCAPABILITY_REASON)
        return cls(capability=capability_, reason=reason_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['capability'] = self.capability
        out['reason'] = self.reason
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class Ack:
    """Acknowledges a request that has no other result."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_ADMITRUN_AGENT_PROFILE = validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None)
_ADMITRUN_SKILLS = validate.sequence(32, validate.text(64, '^[a-z][a-z0-9-]{0,63}$', None))
_ADMITRUN_REQUESTED_CAPABILITIES = validate.sequence(64, validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None))


@dataclass(frozen=True, slots=True, kw_only=True)
class AdmitRun:
    """Asks the kernel to admit a run and mint its authority. `requested_capabilities` is a
    request, not an assertion: the kernel intersects it with the agent profile, the
    skills, the parent grant and the profile ceiling, and returns what survived
    (`CAPABILITIES.md` §4, `mint` step 5). Asking for more is not an error, because an
    error invites a retry loop; it yields less, and the difference is reported. There is
    no `mode`, `profile`, `workspace_sensitivity`, `taint` or `privacy_class` field.
    Those are policy inputs, and ADR-0028 makes every policy input kernel-derived: a
    field here would be the runtime asserting one.
    """

    agent_profile: str
    """Which agent profile the run is for. The kernel resolves it to the profile's declared
    capabilities; an unknown name is a denial, not a protocol error.
    """
    skills: list[str]
    """The skills to activate. Skills only ever narrow."""
    requested_capabilities: list[str]
    """The capabilities the run would like. May exceed what it can have."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('agent_profile', 'skills', 'requested_capabilities'), False, cx)
        agent_profile_ = validate.take_required(known, 'agent_profile', cx, _ADMITRUN_AGENT_PROFILE)
        skills_ = validate.take_required(known, 'skills', cx, _ADMITRUN_SKILLS)
        requested_capabilities_ = validate.take_required(known, 'requested_capabilities', cx, _ADMITRUN_REQUESTED_CAPABILITIES)
        return cls(agent_profile=agent_profile_, skills=skills_, requested_capabilities=requested_capabilities_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['agent_profile'] = self.agent_profile
        skills_out: list[JsonValue] = list(self.skills)
        out['skills'] = skills_out
        requested_capabilities_out: list[JsonValue] = list(self.requested_capabilities)
        out['requested_capabilities'] = requested_capabilities_out
        return out


_AUTHORITYQUERY_PROPOSED = validate.text(512, '^[a-z][a-z0-9_]{0,15}\\.[a-z][a-z0-9_]{0,31}:[A-Za-z0-9._/*:@+~<>-]{1,384}(\\?[A-Za-z0-9_=,&.*/-]{1,96})?$', None)


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthorityQuery:
    """Asks what a run may do, and optionally whether one specific action is permitted.
    Read-only in both shapes. It reports authority and grants none, touches no resource,
    reserves nothing and performs no effect: it is the question M3 exists to answer,
    asked without doing anything about the answer.
    """

    proposed: str | None = None
    """A proposed action, in the kernel's capability grammar. When present the response
    carries a `decision` for exactly this action; when absent the response reports
    effective authority only.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('proposed',), False, cx)
        proposed_ = validate.take_optional(known, 'proposed', cx, _AUTHORITYQUERY_PROPOSED)
        return cls(proposed=proposed_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        if self.proposed is not None:
            out['proposed'] = self.proposed
        return out


_AUTHORITYREFUSAL_OPERATION = validate.enumeration(('ACQUIRE_LEASE', 'RELEASE_LEASE', 'HEARTBEAT', 'ADMIT_RUN', 'RELEASE_RUN', 'QUERY_AUTHORITY'))
_AUTHORITYREFUSAL_REASON = validate.enumeration(('STALE_EPOCH', 'LEASE_HELD', 'IDEMPOTENCY_CONFLICT', 'UNKNOWN_AGENT_PROFILE', 'UNKNOWN_RUN'))
_AUTHORITYREFUSAL_PAIRING = {
    'ACQUIRE_LEASE': ('LEASE_HELD',),
    'RELEASE_LEASE': ('STALE_EPOCH',),
    'HEARTBEAT': ('STALE_EPOCH',),
    'ADMIT_RUN': ('STALE_EPOCH', 'IDEMPOTENCY_CONFLICT', 'UNKNOWN_AGENT_PROFILE'),
    'RELEASE_RUN': ('STALE_EPOCH',),
    'QUERY_AUTHORITY': ('STALE_EPOCH', 'UNKNOWN_RUN'),
}


@dataclass(frozen=True, slots=True, kw_only=True)
class AuthorityRefusal:
    """The authority declined to act on a well-formed request. **Three different things a
    caller must be able to tell apart**, and this is the middle one: *
    `direwolf.protocol.error` — the bytes did not form a valid message. Nothing was
    evaluated because nothing arrived. The remedy is to fix the message. * **this** —
    the message was valid and the authority's own state does not permit the operation to
    be attempted. No policy ran, no capability was consulted. The remedy is named by
    `reason` and is usually to re-acquire a lease, admit a run, or stop retrying. *
    `direwolf.authority.effective` carrying a `DENY` decision — both gates of ADR-0006
    ran against real state and refused. The remedy is to ask for less, or to change
    policy. Merging any two of those to save a message type would leave a caller unable
    to choose between three different remedies, and the failure mode of guessing is a
    retry loop against a refusal that will never change. **Two fields, and no third.**
    There is no `detail` string, no `hint`, no map: `ProtocolErrorPayload` carries a
    detail because a malformed message needs a human to repair *a message*, whereas a
    refusal needs the caller to take one of five known actions. Every byte beyond the
    reason is a byte the authority tells a caller about state the caller could not
    otherwise see — which is how a refusal becomes an oracle. `STALE_EPOCH` in
    particular does **not** carry the kernel's current epoch: handing a fenced runtime
    the one value it needs to un-fence itself would undo the fencing.
    """

    operation: str
    """Which operation was refused. Redundant with `causation_id` for a caller that still
    has the request; not redundant for an audit record, and it is what closes the
    pairing below.
    """
    reason: str
    """Why. Closed, and narrower still per operation."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('operation', 'reason'), False, cx)
        operation_ = validate.take_required(known, 'operation', cx, _AUTHORITYREFUSAL_OPERATION)
        reason_ = validate.take_required(known, 'reason', cx, _AUTHORITYREFUSAL_REASON)
        validate.paired('operation', operation_, 'reason', reason_, _AUTHORITYREFUSAL_PAIRING, cx)
        return cls(operation=operation_, reason=reason_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['operation'] = self.operation
        out['reason'] = self.reason
        return out


_EFFECTIVEAUTHORITY_RUN_ID = validate.identifier('run')
_EFFECTIVEAUTHORITY_EPOCH = validate.integer(1, 9007199254740991)
_EFFECTIVEAUTHORITY_POLICY_REVISION = validate.text(64, '^[0-9a-f]{64}$', None)
_EFFECTIVEAUTHORITY_PROFILE = validate.enumeration(('SAFE', 'BALANCED', 'POWER'))


@dataclass(frozen=True, slots=True, kw_only=True)
class EffectiveAuthority:
    """What a run may do, as the kernel currently records it."""

    run_id: str
    """The run this describes."""
    epoch: int
    """The epoch the answer is current at. An answer is about a moment."""
    policy_revision: str
    """Which policy produced it."""
    profile: str
    """The ceiling the run was admitted under."""
    granted: list[CapabilityGrant]
    """What the run holds."""
    withheld: list[WithheldCapability]
    """What it asked for and did not get."""
    decision: AuthorityDecision | None = None
    """The decision for the `proposed` action, present exactly when the query carried one.
    The kernel guarantees the correspondence; a reader that asked and received none must
    treat the answer as unusable rather than as an allow.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('run_id', 'epoch', 'policy_revision', 'profile', 'granted', 'withheld', 'decision'), False, cx)
        run_id_ = validate.take_required(known, 'run_id', cx, _EFFECTIVEAUTHORITY_RUN_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _EFFECTIVEAUTHORITY_EPOCH)
        policy_revision_ = validate.take_required(known, 'policy_revision', cx, _EFFECTIVEAUTHORITY_POLICY_REVISION)
        profile_ = validate.take_required(known, 'profile', cx, _EFFECTIVEAUTHORITY_PROFILE)
        granted_ = validate.take_required(known, 'granted', cx, validate.sequence(64, CapabilityGrant.decode))
        withheld_ = validate.take_required(known, 'withheld', cx, validate.sequence(64, WithheldCapability.decode))
        decision_ = validate.take_optional(known, 'decision', cx, AuthorityDecision.decode)
        return cls(run_id=run_id_, epoch=epoch_, policy_revision=policy_revision_, profile=profile_, granted=granted_, withheld=withheld_, decision=decision_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['run_id'] = self.run_id
        out['epoch'] = self.epoch
        out['policy_revision'] = self.policy_revision
        out['profile'] = self.profile
        granted_out: list[JsonValue] = [item.encode() for item in self.granted]
        out['granted'] = granted_out
        withheld_out: list[JsonValue] = [item.encode() for item in self.withheld]
        out['withheld'] = withheld_out
        if self.decision is not None:
            out['decision'] = self.decision.encode()
        return out


_HANDSHAKE_MIN_VERSION = validate.integer(1, 65535)
_HANDSHAKE_MAX_VERSION = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class Handshake:
    """Opens a DWKP connection by offering a range of envelope versions. Always sent in
    envelope version 1, whatever it offers, so that any receiver can read the offer.
    """

    min_version: int
    """Lowest envelope version the sender speaks."""
    max_version: int
    """Highest envelope version the sender speaks."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('min_version', 'max_version'), False, cx)
        min_version_ = validate.take_required(known, 'min_version', cx, _HANDSHAKE_MIN_VERSION)
        max_version_ = validate.take_required(known, 'max_version', cx, _HANDSHAKE_MAX_VERSION)
        validate.ordered('min_version', min_version_, 'max_version', max_version_, cx)
        return cls(min_version=min_version_, max_version=max_version_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['min_version'] = self.min_version
        out['max_version'] = self.max_version
        return out


_HANDSHAKEACCEPTED_VERSION = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class HandshakeAccepted:
    """Accepts a handshake, naming the version both sides will use: the highest both
    support at or above the receiver's floor.
    """

    version: int
    """The negotiated envelope version."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('version',), False, cx)
        version_ = validate.take_required(known, 'version', cx, _HANDSHAKEACCEPTED_VERSION)
        return cls(version=version_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['version'] = self.version
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class HeartbeatPayload:
    """Renews the session lease named in the envelope at the epoch named in the envelope.
    Carries nothing else.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseAcquire:
    """Requests the single-writer lease for the session named in the envelope. The kernel
    assigns the epoch; the sender cannot propose one.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_LEASEGRANT_SESSION_ID = validate.identifier('ses')
_LEASEGRANT_EPOCH = validate.integer(1, 9007199254740991)


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseGrant:
    """The lease the kernel granted."""

    session_id: str
    """The session the lease is for."""
    epoch: int
    """The epoch the kernel assigned. Every later request for the session carries it; a
    request carrying an older one is fenced (§3).
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('session_id', 'epoch'), False, cx)
        session_id_ = validate.take_required(known, 'session_id', cx, _LEASEGRANT_SESSION_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _LEASEGRANT_EPOCH)
        return cls(session_id=session_id_, epoch=epoch_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['session_id'] = self.session_id
        out['epoch'] = self.epoch
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseRelease:
    """Surrenders the lease named in the envelope, at the epoch named in the envelope. Can
    only reduce authority.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_PROTOCOLERRORPAYLOAD_CODE = validate.enumeration(('PROTOCOL_FRAME_EMPTY', 'PROTOCOL_FRAME_TOO_LARGE', 'PROTOCOL_FRAME_TRUNCATED', 'PROTOCOL_CONTENT_TYPE_UNSUPPORTED', 'PROTOCOL_INVALID_UTF8', 'PROTOCOL_INVALID_JSON', 'PROTOCOL_DUPLICATE_KEY', 'PROTOCOL_MAX_DEPTH_EXCEEDED', 'PROTOCOL_NUMBER_OUT_OF_DOMAIN', 'PROTOCOL_VERSION_UNSUPPORTED', 'PROTOCOL_UNKNOWN_OPERATION', 'PROTOCOL_SCHEMA_VIOLATION'))
_PROTOCOLERRORPAYLOAD_VIOLATION = validate.enumeration(('UNKNOWN_FIELD', 'MISSING_FIELD', 'FORBIDDEN_FIELD', 'WRONG_TYPE', 'NULL_NOT_ALLOWED', 'OUT_OF_RANGE', 'TOO_LONG', 'INVALID_FORMAT', 'UNKNOWN_VARIANT', 'TOO_MANY_ITEMS', 'INCONSISTENT'))
_PROTOCOLERRORPAYLOAD_PATH = validate.text(256, '^(/[\\s\\S]*)?$', None)
_PROTOCOLERRORPAYLOAD_DETAIL = validate.text(512, None, None)


@dataclass(frozen=True, slots=True, kw_only=True)
class ProtocolErrorPayload:
    """The message did not decode. This is **not** a policy denial: nothing was evaluated,
    because there was nothing well-formed to evaluate.
    """

    code: str
    """Stable error code."""
    violation: str | None = None
    """Finer classification for schema and version failures."""
    path: str | None = None
    """JSON Pointer to the failing location."""
    detail: str
    """Short explanation. Informational; bounded."""
    supported: VersionSpan | None = None
    """For version failures, the range the receiver supports."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('code', 'violation', 'path', 'detail', 'supported'), False, cx)
        code_ = validate.take_required(known, 'code', cx, _PROTOCOLERRORPAYLOAD_CODE)
        violation_ = validate.take_optional(known, 'violation', cx, _PROTOCOLERRORPAYLOAD_VIOLATION)
        path_ = validate.take_optional(known, 'path', cx, _PROTOCOLERRORPAYLOAD_PATH)
        detail_ = validate.take_required(known, 'detail', cx, _PROTOCOLERRORPAYLOAD_DETAIL)
        supported_ = validate.take_optional(known, 'supported', cx, VersionSpan.decode)
        return cls(code=code_, violation=violation_, path=path_, detail=detail_, supported=supported_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['code'] = self.code
        if self.violation is not None:
            out['violation'] = self.violation
        if self.path is not None:
            out['path'] = self.path
        out['detail'] = self.detail
        if self.supported is not None:
            out['supported'] = self.supported.encode()
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class ReleaseRun:
    """Ends a run's authority. The run is named by the envelope. Carries nothing: it can
    only surrender authority, and a field here would be a way to say something about a
    run while ending it.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_RUNGRANT_RUN_ID = validate.identifier('run')
_RUNGRANT_EPOCH = validate.integer(1, 9007199254740991)
_RUNGRANT_POLICY_REVISION = validate.text(64, '^[0-9a-f]{64}$', None)
_RUNGRANT_PROFILE = validate.enumeration(('SAFE', 'BALANCED', 'POWER'))


@dataclass(frozen=True, slots=True, kw_only=True)
class RunGrant:
    """The authority the kernel minted for a run. Everything here is kernel-assigned. The
    run id, the epoch and every `cap_id` are the kernel's; the runtime cannot propose
    any of them.
    """

    run_id: str
    """The run the kernel admitted."""
    epoch: int
    """The epoch this grant is fenced to. A request carrying an older one is rejected
    (`PROTOCOL.md` §3).
    """
    policy_revision: str
    """Which policy was in force when the grant was minted."""
    profile: str
    """The ceiling the run was admitted under."""
    granted: list[CapabilityGrant]
    """What the run holds."""
    withheld: list[WithheldCapability]
    """What it asked for and did not get, so it can say so coherently."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('run_id', 'epoch', 'policy_revision', 'profile', 'granted', 'withheld'), False, cx)
        run_id_ = validate.take_required(known, 'run_id', cx, _RUNGRANT_RUN_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _RUNGRANT_EPOCH)
        policy_revision_ = validate.take_required(known, 'policy_revision', cx, _RUNGRANT_POLICY_REVISION)
        profile_ = validate.take_required(known, 'profile', cx, _RUNGRANT_PROFILE)
        granted_ = validate.take_required(known, 'granted', cx, validate.sequence(64, CapabilityGrant.decode))
        withheld_ = validate.take_required(known, 'withheld', cx, validate.sequence(64, WithheldCapability.decode))
        return cls(run_id=run_id_, epoch=epoch_, policy_revision=policy_revision_, profile=profile_, granted=granted_, withheld=withheld_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['run_id'] = self.run_id
        out['epoch'] = self.epoch
        out['policy_revision'] = self.policy_revision
        out['profile'] = self.profile
        granted_out: list[JsonValue] = [item.encode() for item in self.granted]
        out['granted'] = granted_out
        withheld_out: list[JsonValue] = [item.encode() for item in self.withheld]
        out['withheld'] = withheld_out
        return out


MESSAGES: Final[Mapping[tuple[str, str], MessageSpec]] = MappingProxyType({
    ('response', 'direwolf.ack'): MessageSpec(
        schema='direwolf.ack',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=Ack,
    ),
    ('response', 'direwolf.authority.effective'): MessageSpec(
        schema='direwolf.authority.effective',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=EffectiveAuthority,
    ),
    ('request', 'direwolf.authority.query'): MessageSpec(
        schema='direwolf.authority.query',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'required', 'required', 'forbidden'),
        payload=AuthorityQuery,
    ),
    ('response', 'direwolf.authority.refused'): MessageSpec(
        schema='direwolf.authority.refused',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=AuthorityRefusal,
    ),
    ('response', 'direwolf.handshake.accepted'): MessageSpec(
        schema='direwolf.handshake.accepted',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=HandshakeAccepted,
    ),
    ('request', 'direwolf.handshake'): MessageSpec(
        schema='direwolf.handshake',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=Handshake,
    ),
    ('request', 'direwolf.heartbeat'): MessageSpec(
        schema='direwolf.heartbeat',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'forbidden'),
        payload=HeartbeatPayload,
    ),
    ('request', 'direwolf.lease.acquire'): MessageSpec(
        schema='direwolf.lease.acquire',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseAcquire,
    ),
    ('response', 'direwolf.lease.grant'): MessageSpec(
        schema='direwolf.lease.grant',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseGrant,
    ),
    ('request', 'direwolf.lease.release'): MessageSpec(
        schema='direwolf.lease.release',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'forbidden'),
        payload=LeaseRelease,
    ),
    ('response', 'direwolf.protocol.error'): MessageSpec(
        schema='direwolf.protocol.error',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ProtocolErrorPayload,
    ),
    ('request', 'direwolf.run.admit'): MessageSpec(
        schema='direwolf.run.admit',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'required'),
        payload=AdmitRun,
    ),
    ('response', 'direwolf.run.grant'): MessageSpec(
        schema='direwolf.run.grant',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=RunGrant,
    ),
    ('request', 'direwolf.run.release'): MessageSpec(
        schema='direwolf.run.release',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'required', 'required', 'forbidden'),
        payload=ReleaseRun,
    ),
})
"""Every message of this family the build knows, keyed by (type, schema)."""


def decode_body(data: bytes) -> envelope.DwkpMessage:
    """Decode a DWKP frame body; rejects everything dwk-proto rejects."""
    return envelope.decode_dwkp(data, MESSAGES)


def encode(message: envelope.DwkpMessage) -> bytes:
    """Canonical bytes for a message, verified by re-decoding."""
    return envelope.encode_dwkp(message, MESSAGES)


def to_frame(message: envelope.DwkpMessage) -> bytes:
    """A complete frame for a message."""
    return envelope.frame_dwkp(message, MESSAGES)
