# GENERATED by scripts/gen_proto_python.py from schemas/dwkp/. DO NOT EDIT.
# Source digest: sha256:9aa98367a2be28351b63bd3fa4ac0d5247ba4a4ba314e6382fdc42603dba3db9
"""DWKP -- the kernel protocol. Strict: unknown fields and operations are rejected."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Final, Self

from direwolf.wire import envelope, validate
from direwolf.wire.envelope import MessageSpec, Rules
from direwolf.wire.errors import VersionRange
from direwolf.wire.strict_json import JsonValue
from direwolf.wire.validate import Cx

__all__ = [
    "MESSAGES",
    "Ack",
    "Handshake",
    "HandshakeAccepted",
    "HeartbeatPayload",
    "LeaseAcquire",
    "LeaseGrant",
    "LeaseRelease",
    "ProtocolErrorPayload",
    "VersionSpan",
]


_VERSIONSPAN_MIN = validate.integer(1, 65535)
_VERSIONSPAN_MAX = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class VersionSpan:
    """A range of versions a receiver supports."""

    min: int
    """Lowest supported version."""
    max: int
    """Highest supported version."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('min', 'max'), False, cx)
        min_ = validate.take_required(known, 'min', cx, _VERSIONSPAN_MIN)
        max_ = validate.take_required(known, 'max', cx, _VERSIONSPAN_MAX)
        validate.ordered('min', min_, 'max', max_, cx)
        return cls(min=min_, max=max_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['min'] = self.min
        out['max'] = self.max
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class Ack:
    """Acknowledges a request that has no other result."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_HANDSHAKE_MIN_VERSION = validate.integer(1, 65535)
_HANDSHAKE_MAX_VERSION = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class Handshake:
    """Opens a DWKP connection by offering a range of envelope versions. Always sent in
    envelope version 1, whatever it offers, so that any receiver can read the offer.
    """

    min_version: int
    """Lowest envelope version the sender speaks."""
    max_version: int
    """Highest envelope version the sender speaks."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('min_version', 'max_version'), False, cx)
        min_version_ = validate.take_required(known, 'min_version', cx, _HANDSHAKE_MIN_VERSION)
        max_version_ = validate.take_required(known, 'max_version', cx, _HANDSHAKE_MAX_VERSION)
        validate.ordered('min_version', min_version_, 'max_version', max_version_, cx)
        return cls(min_version=min_version_, max_version=max_version_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['min_version'] = self.min_version
        out['max_version'] = self.max_version
        return out


_HANDSHAKEACCEPTED_VERSION = validate.integer(1, 65535)


@dataclass(frozen=True, slots=True, kw_only=True)
class HandshakeAccepted:
    """Accepts a handshake, naming the version both sides will use: the highest both
    support at or above the receiver's floor.
    """

    version: int
    """The negotiated envelope version."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('version',), False, cx)
        version_ = validate.take_required(known, 'version', cx, _HANDSHAKEACCEPTED_VERSION)
        return cls(version=version_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['version'] = self.version
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class HeartbeatPayload:
    """Renews the session lease named in the envelope at the epoch named in the envelope.
    Carries nothing else.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseAcquire:
    """Requests the single-writer lease for the session named in the envelope. The kernel
    assigns the epoch; the sender cannot propose one.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_LEASEGRANT_SESSION_ID = validate.identifier('ses')
_LEASEGRANT_EPOCH = validate.integer(1, 9007199254740991)


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseGrant:
    """The lease the kernel granted."""

    session_id: str
    """The session the lease is for."""
    epoch: int
    """The epoch the kernel assigned. Every later request for the session carries it; a
    request carrying an older one is fenced (§3).
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('session_id', 'epoch'), False, cx)
        session_id_ = validate.take_required(known, 'session_id', cx, _LEASEGRANT_SESSION_ID)
        epoch_ = validate.take_required(known, 'epoch', cx, _LEASEGRANT_EPOCH)
        return cls(session_id=session_id_, epoch=epoch_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['session_id'] = self.session_id
        out['epoch'] = self.epoch
        return out


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseRelease:
    """Surrenders the lease named in the envelope, at the epoch named in the envelope. Can
    only reduce authority.
    """

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        _known, _extensions = validate.partition(obj, (), False, cx)
        return cls()

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        return out


_PROTOCOLERRORPAYLOAD_CODE = validate.enumeration(('PROTOCOL_FRAME_EMPTY', 'PROTOCOL_FRAME_TOO_LARGE', 'PROTOCOL_FRAME_TRUNCATED', 'PROTOCOL_CONTENT_TYPE_UNSUPPORTED', 'PROTOCOL_INVALID_UTF8', 'PROTOCOL_INVALID_JSON', 'PROTOCOL_DUPLICATE_KEY', 'PROTOCOL_MAX_DEPTH_EXCEEDED', 'PROTOCOL_NUMBER_OUT_OF_DOMAIN', 'PROTOCOL_VERSION_UNSUPPORTED', 'PROTOCOL_UNKNOWN_OPERATION', 'PROTOCOL_SCHEMA_VIOLATION'))
_PROTOCOLERRORPAYLOAD_VIOLATION = validate.enumeration(('UNKNOWN_FIELD', 'MISSING_FIELD', 'FORBIDDEN_FIELD', 'WRONG_TYPE', 'NULL_NOT_ALLOWED', 'OUT_OF_RANGE', 'TOO_LONG', 'INVALID_FORMAT', 'UNKNOWN_VARIANT', 'TOO_MANY_ITEMS', 'INCONSISTENT'))
_PROTOCOLERRORPAYLOAD_PATH = validate.text(256, '^(/[\\s\\S]*)?$', None)
_PROTOCOLERRORPAYLOAD_DETAIL = validate.text(512, None, None)


@dataclass(frozen=True, slots=True, kw_only=True)
class ProtocolErrorPayload:
    """The message did not decode. This is **not** a policy denial: nothing was evaluated,
    because there was nothing well-formed to evaluate.
    """

    code: str
    """Stable error code."""
    violation: str | None = None
    """Finer classification for schema and version failures."""
    path: str | None = None
    """JSON Pointer to the failing location."""
    detail: str
    """Short explanation. Informational; bounded."""
    supported: VersionSpan | None = None
    """For version failures, the range the receiver supports."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, _extensions = validate.partition(obj, ('code', 'violation', 'path', 'detail', 'supported'), False, cx)
        code_ = validate.take_required(known, 'code', cx, _PROTOCOLERRORPAYLOAD_CODE)
        violation_ = validate.take_optional(known, 'violation', cx, _PROTOCOLERRORPAYLOAD_VIOLATION)
        path_ = validate.take_optional(known, 'path', cx, _PROTOCOLERRORPAYLOAD_PATH)
        detail_ = validate.take_required(known, 'detail', cx, _PROTOCOLERRORPAYLOAD_DETAIL)
        supported_ = validate.take_optional(known, 'supported', cx, VersionSpan.decode)
        return cls(code=code_, violation=violation_, path=path_, detail=detail_, supported=supported_)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['code'] = self.code
        if self.violation is not None:
            out['violation'] = self.violation
        if self.path is not None:
            out['path'] = self.path
        out['detail'] = self.detail
        if self.supported is not None:
            out['supported'] = self.supported.encode()
        return out


MESSAGES: Final[Mapping[tuple[str, str], MessageSpec]] = MappingProxyType({
    ('response', 'direwolf.ack'): MessageSpec(
        schema='direwolf.ack',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=Ack,
    ),
    ('response', 'direwolf.handshake.accepted'): MessageSpec(
        schema='direwolf.handshake.accepted',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=HandshakeAccepted,
    ),
    ('request', 'direwolf.handshake'): MessageSpec(
        schema='direwolf.handshake',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=Handshake,
    ),
    ('request', 'direwolf.heartbeat'): MessageSpec(
        schema='direwolf.heartbeat',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'forbidden'),
        payload=HeartbeatPayload,
    ),
    ('request', 'direwolf.lease.acquire'): MessageSpec(
        schema='direwolf.lease.acquire',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseAcquire,
    ),
    ('response', 'direwolf.lease.grant'): MessageSpec(
        schema='direwolf.lease.grant',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'required', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseGrant,
    ),
    ('request', 'direwolf.lease.release'): MessageSpec(
        schema='direwolf.lease.release',
        message_type='request',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'required', 'forbidden'),
        payload=LeaseRelease,
    ),
    ('response', 'direwolf.protocol.error'): MessageSpec(
        schema='direwolf.protocol.error',
        message_type='response',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'forbidden', 'forbidden', 'forbidden', 'forbidden'),
        payload=ProtocolErrorPayload,
    ),
})
"""Every message of this family the build knows, keyed by (type, schema)."""


def decode_body(data: bytes) -> envelope.DwkpMessage:
    """Decode a DWKP frame body; rejects everything dwk-proto rejects."""
    return envelope.decode_dwkp(data, MESSAGES)


def encode(message: envelope.DwkpMessage) -> bytes:
    """Canonical bytes for a message, verified by re-decoding."""
    return envelope.encode_dwkp(message, MESSAGES)


def to_frame(message: envelope.DwkpMessage) -> bytes:
    """A complete frame for a message."""
    return envelope.frame_dwkp(message, MESSAGES)
