# GENERATED by scripts/gen_proto_python.py from schemas/events/. DO NOT EDIT.
# Source digest: sha256:25f5370c3006eea13b2b350de3c42dd7742e7a9380b51ea0bd294247f0a03946
"""Event-log records. Retained verbatim; unknown events are kept, not dropped."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType
from typing import Final, Self

from direwolf.wire import envelope, validate
from direwolf.wire.envelope import MessageSpec, Rules
from direwolf.wire.errors import VersionRange
from direwolf.wire.strict_json import JsonValue
from direwolf.wire.validate import Cx

__all__ = [
    "MESSAGES",
    "LeaseAcquired",
]


_LEASEACQUIRED_EPOCH = validate.integer(1, 9007199254740991)


@dataclass(frozen=True, slots=True, kw_only=True)
class LeaseAcquired:
    """The runtime acquired the lease for the session in the envelope. A **cache** of a
    kernel fact: the kernel assigned the epoch and holds the authoritative value in
    `kernel.db` (ADR-0028). Where this record and the kernel disagree, the kernel is
    right.
    """

    epoch: int
    """The epoch the kernel granted."""
    extensions: dict[str, JsonValue] = field(default_factory=dict)
    """Members this version does not declare, preserved for re-emission."""

    @classmethod
    def decode(cls, value: JsonValue, cx: Cx) -> Self:
        obj = validate.expect_object(value, cx)
        known, extensions = validate.partition(obj, ('epoch',), True, cx)
        epoch_ = validate.take_required(known, 'epoch', cx, _LEASEACQUIRED_EPOCH)
        return cls(epoch=epoch_, extensions=extensions)

    def encode(self) -> dict[str, JsonValue]:
        out: dict[str, JsonValue] = {}
        out['epoch'] = self.epoch
        for key, member in self.extensions.items():
            out[key] = member
        return out


MESSAGES: Final[Mapping[tuple[str, str], MessageSpec]] = MappingProxyType({
    ('event', 'direwolf.session.lease_acquired'): MessageSpec(
        schema='direwolf.session.lease_acquired',
        message_type='event',
        versions=VersionRange(1, 1),
        rules=Rules('optional', 'optional', 'required', 'forbidden', 'forbidden', 'forbidden'),
        payload=LeaseAcquired,
    ),
})
"""Every message of this family the build knows, keyed by (type, schema)."""


def read(data: bytes) -> envelope.EventRecord:
    """Read a record; its bytes are always retained verbatim."""
    return envelope.read_event(data, MESSAGES)
