# GENERATED by scripts/gen_proto_python.py from schemas/dwkp/operations.json. DO NOT EDIT.
# Source digest: sha256:396c2b33fc13990ad024caf30a7a70a1b60427b0b3c227da79bafae96fb5c5e0
"""The DWKP operation inventory. See docs/DWKP_OPERATIONS.md for the second-path
argument behind each entry; this module carries only what code needs."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True, slots=True, kw_only=True)
class Operation:
    """One inventory entry."""

    name: str
    layer: str
    status: str
    request: str | None
    responses: tuple[str, ...]
    semantics_owner: str
    effect_bearing: bool
    authority_bearing: bool


OPERATIONS: Final[tuple[Operation, ...]] = (
    Operation(
        name='Handshake',
        layer='protocol-control',
        status='defined',
        request='direwolf.handshake',
        responses=('direwolf.handshake.accepted', 'direwolf.protocol.error'),
        semantics_owner='M3',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='Heartbeat',
        layer='authority-primitive',
        status='defined',
        request='direwolf.heartbeat',
        responses=('direwolf.ack', 'direwolf.authority.refused', 'direwolf.protocol.error'),
        semantics_owner='M3 (epoch authority); M8 (lease renewal)',
        effect_bearing=False,
        authority_bearing=True,
    ),
    Operation(
        name='AcquireLease',
        layer='authority-primitive',
        status='defined',
        request='direwolf.lease.acquire',
        responses=('direwolf.lease.grant', 'direwolf.authority.refused', 'direwolf.protocol.error'),
        semantics_owner='M3 (epoch authority); M8 (session leases)',
        effect_bearing=False,
        authority_bearing=True,
    ),
    Operation(
        name='ReleaseLease',
        layer='authority-primitive',
        status='defined',
        request='direwolf.lease.release',
        responses=('direwolf.ack', 'direwolf.authority.refused', 'direwolf.protocol.error'),
        semantics_owner='M3; M8',
        effect_bearing=False,
        authority_bearing=True,
    ),
    Operation(
        name='AdmitRun',
        layer='authority-primitive',
        status='defined',
        request='direwolf.run.admit',
        responses=('direwolf.run.grant', 'direwolf.authority.refused', 'direwolf.protocol.error'),
        semantics_owner='M3',
        effect_bearing=False,
        authority_bearing=True,
    ),
    Operation(
        name='ReleaseRun',
        layer='authority-primitive',
        status='defined',
        request='direwolf.run.release',
        responses=('direwolf.ack', 'direwolf.authority.refused', 'direwolf.protocol.error'),
        semantics_owner='M3',
        effect_bearing=False,
        authority_bearing=True,
    ),
    Operation(
        name='ToolInvoke',
        layer='authority-primitive',
        status='defined',
        request='direwolf.tool.invoke',
        responses=('direwolf.tool.result', 'direwolf.tool.denied', 'direwolf.tool.refused', 'direwolf.tool.failed', 'direwolf.protocol.error'),
        semantics_owner='M4b (fs.read, version 1); M4c (the eight filesystem tools, version 2); M4d (the three process tools, version 3); M4e, M5, M10 (further tools)',
        effect_bearing=True,
        authority_bearing=True,
    ),
    Operation(
        name='ToolCancel',
        layer='authority-primitive',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M9',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='ModelCall',
        layer='authority-primitive',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M7',
        effect_bearing=True,
        authority_bearing=True,
    ),
    Operation(
        name='CanonicalPreview',
        layer='authority-primitive',
        status='defined',
        request='direwolf.tool.preview',
        responses=('direwolf.tool.previewed', 'direwolf.tool.refused', 'direwolf.protocol.error'),
        semantics_owner='M4b (version 1); M4c (version 2); M4d (version 3)',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='CreateArtifact',
        layer='authority-primitive',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M12',
        effect_bearing=True,
        authority_bearing=False,
    ),
    Operation(
        name='ReadArtifact',
        layer='authority-primitive',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M12',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='QueryBudget',
        layer='authority-primitive',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M6',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='QueryAuthority',
        layer='authority-primitive',
        status='defined',
        request='direwolf.authority.query',
        responses=('direwolf.authority.effective', 'direwolf.authority.refused', 'direwolf.protocol.error'),
        semantics_owner='M3',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='QueryInvocationStatus',
        layer='authority-primitive',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M9',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='ListVisibleTools',
        layer='runtime-convenience',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M10',
        effect_bearing=False,
        authority_bearing=False,
    ),
    Operation(
        name='SpawnSubagent',
        layer='runtime-convenience',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M14',
        effect_bearing=False,
        authority_bearing=True,
    ),
    Operation(
        name='McpOpen',
        layer='runtime-convenience',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M16',
        effect_bearing=True,
        authority_bearing=True,
    ),
    Operation(
        name='McpClose',
        layer='runtime-convenience',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M16',
        effect_bearing=True,
        authority_bearing=False,
    ),
    Operation(
        name='ChannelSend',
        layer='runtime-convenience',
        status='reserved',
        request=None,
        responses=(),
        semantics_owner='M20',
        effect_bearing=True,
        authority_bearing=True,
    ),
)
